{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f6cb14d3-149d-403d-b009-2512cf43bd39",
   "metadata": {},
   "outputs": [],
   "source": [
    "# %pip install tcrdist3\n",
    "import tcrdist"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "53b49f8f-a32f-4cda-b151-e37e0c7ff457",
   "metadata": {},
   "outputs": [],
   "source": [
    "from matplotlib import pyplot as plt\n",
    "from eindex.numpy import argsort, gather_scatter\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "afe4c77a-434c-4b54-90f9-794b1e8ba1f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "if False:\n",
    "    vdj_df = pd.read_csv('./VDJdb_paired_chain.csv')\n",
    "    is_good = ~(vdj_df['CDR3a_extended'].isna() | vdj_df['CDR3b_extended'].isna())\n",
    "    paired_TRA = vdj_df['CDR3a_extended'][is_good].tolist()\n",
    "    paired_TRB = vdj_df['CDR3b_extended'][is_good].tolist()\n",
    "    \n",
    "    pep_lookup, paired_pep = np.unique(vdj_df['Peptide'][is_good], return_inverse=True)\n",
    "    peptide_ids = paired_pep\n",
    "else:\n",
    "    vdj_df = pd.read_csv('/Users/axelr/Downloads/vdjdb.tsv', sep='\\t')\n",
    "\n",
    "    paired_TRA = []\n",
    "    paired_TRB = []\n",
    "    peptides = []\n",
    "    v_a_gene = []\n",
    "    v_b_gene = []\n",
    "    for _, group in vdj_df[vdj_df['complex.id'] != 0].groupby('complex.id'):\n",
    "        # print(group)\n",
    "        if len(group) != 2:\n",
    "            continue\n",
    "        if group['Score'].iloc[0] == 0:\n",
    "            continue\n",
    "    \n",
    "        group = group.sort_values(by='Gene')\n",
    "        _tra, _trb = group['CDR3']\n",
    "    \n",
    "        paired_TRA.append(_tra)\n",
    "        paired_TRB.append(_trb)\n",
    "        v_a_gene.append(group['V'].iloc[0])\n",
    "        v_b_gene.append(group['V'].iloc[1])\n",
    "        peptides.append(group['Epitope'].iloc[0])\n",
    "        \n",
    "    pep_lookup, paired_pep = np.unique(peptides, return_inverse=True)\n",
    "    peptide_ids = paired_pep\n",
    "\n",
    "    df_tcr = pd.DataFrame({\n",
    "        'cdr3_a_aa': paired_TRA,\n",
    "        'cdr3_b_aa': paired_TRB,\n",
    "        'v_a_gene': v_a_gene,\n",
    "        'v_b_gene': v_b_gene,\n",
    "        'peptide': peptides,\n",
    "        'peptide_id': peptide_ids,\n",
    "    })\n",
    "    df_tcr = df_tcr.drop_duplicates()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cce69db0-8b50-47df-bb1a-668058710d7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "_, counts = np.unique(peptides, return_counts=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "25400b7d-4b69-4d99-893a-694f36f95374",
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import Counter\n",
    "\n",
    "if False:\n",
    "    # kmer stats\n",
    "    def kmers(seq: str, k=3) -> list[str]:\n",
    "        return [seq[i:i+k] for i in range(len(seq) - k + 1)]\n",
    "    \n",
    "    def count_kmers(seq: list[str], k) -> dict[str, int]:\n",
    "        counter = Counter()\n",
    "        for s in seq:\n",
    "            for kmer in kmers(s, k):\n",
    "                counter[kmer] += 1\n",
    "        return counter\n",
    "\n",
    "    for k in [2, 3, 4, 5]:\n",
    "        counts = count_kmers(peptides, k)\n",
    "        print()\n",
    "        for minimal in [1, 2, 3, 4, 5]:\n",
    "            print(k, minimal, sum(v >= minimal for k, v in counts.items()))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b01771e8-296f-434c-9ef0-1f97c7bd3ecd",
   "metadata": {},
   "source": [
    "## TCR dist"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "38937a8b-df2d-4030-9f9b-5cb4bc38d951",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['TRAV1*01', 'TRAV1-1*01', 'TRAV1-2*01', 'TRAV10*01', 'TRAV10N*01',\n",
       "       'TRAV11*02', 'TRAV12-1*01', 'TRAV12-2*01', 'TRAV12-3*01',\n",
       "       'TRAV12D-1*01', 'TRAV12N-2*01', 'TRAV12N-3*01', 'TRAV13-1*01',\n",
       "       'TRAV13-2*01', 'TRAV13-5*01', 'TRAV13N-2*01', 'TRAV14-1*01',\n",
       "       'TRAV14-2*02', 'TRAV14-3*01', 'TRAV14/DV4*01', 'TRAV14/DV4*02',\n",
       "       'TRAV14D-1*01', 'TRAV14D-2*01', 'TRAV14D-3/DV8*01',\n",
       "       'TRAV14D-3/DV8*02', 'TRAV14D-3/DV8*08', 'TRAV14N-1*01',\n",
       "       'TRAV14N-2*01', 'TRAV14N-3*01', 'TRAV15-1/DV6-1*01',\n",
       "       'TRAV15N-1*01', 'TRAV16*01', 'TRAV16D/DV11*01', 'TRAV16D/DV11*02',\n",
       "       'TRAV16N*01', 'TRAV17*01', 'TRAV18*01', 'TRAV19*01', 'TRAV2*01',\n",
       "       'TRAV20*01', 'TRAV21*01', 'TRAV21/DV12*01', 'TRAV22*01',\n",
       "       'TRAV23/DV6*01', 'TRAV24*01', 'TRAV25*01', 'TRAV26-1*01',\n",
       "       'TRAV26-2*01', 'TRAV27*01', 'TRAV29/DV5*01', 'TRAV3*01',\n",
       "       'TRAV3-1*01', 'TRAV3-3*01', 'TRAV3-4*01', 'TRAV30*01', 'TRAV34*01',\n",
       "       'TRAV35*01', 'TRAV36/DV7*01', 'TRAV38-1*01', 'TRAV38-2/DV8*01',\n",
       "       'TRAV39*01', 'TRAV3D-3*02', 'TRAV3N-3*01', 'TRAV4*01',\n",
       "       'TRAV4-2*01', 'TRAV4-2*02', 'TRAV4-4/DV10*01', 'TRAV40*01',\n",
       "       'TRAV41*01', 'TRAV4D-3*01', 'TRAV4D-4*01', 'TRAV4N-3*01',\n",
       "       'TRAV4N-4*01', 'TRAV5*01', 'TRAV5-1*01', 'TRAV5N-4*01', 'TRAV6*01',\n",
       "       'TRAV6-1*01', 'TRAV6-2*01', 'TRAV6-3*01', 'TRAV6-4*03',\n",
       "       'TRAV6-5*04', 'TRAV6-6*01', 'TRAV6-7/DV9*01', 'TRAV6D-3*01',\n",
       "       'TRAV6D-4*01', 'TRAV6D-5*01', 'TRAV6D-6*02', 'TRAV6D-7*01',\n",
       "       'TRAV6N-5*01', 'TRAV6N-6*01', 'TRAV6N-7*01', 'TRAV7-1*01',\n",
       "       'TRAV7-2*02', 'TRAV7-3*04', 'TRAV7-4*01', 'TRAV7-5*01',\n",
       "       'TRAV7D-2*01', 'TRAV7D-3*01', 'TRAV7D-4*01', 'TRAV7D-5*01',\n",
       "       'TRAV7N-4*01', 'TRAV7N-5*01', 'TRAV7N-6*01', 'TRAV8-1*01',\n",
       "       'TRAV8-2*01', 'TRAV8-3*01', 'TRAV8-4*01', 'TRAV8-6*01',\n",
       "       'TRAV8-6*02', 'TRAV8D-1*01', 'TRAV8D-2*03', 'TRAV8N-2*01',\n",
       "       'TRAV9-1*01', 'TRAV9-1*02', 'TRAV9-2*01', 'TRAV9-4*01',\n",
       "       'TRAV9D-3*01', 'TRAV9N-2*01', 'TRAV9N-3*01', 'TRAV9N-4*01'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_tcr['v_a_gene'].sort_values().unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d9811c96-4428-4657-b640-ee37e5b26c1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "if True:\n",
    "    pass\n",
    "else:\n",
    "    vdj_df = pd.read_csv('VDJdb_paired_chain.csv', sep='\\t')\n",
    "    # is_good = ~(vdj_df['CDR3a_extended'].isna() | vdj_df['CDR3b_extended'].isna())    \n",
    "    \n",
    "    # drop duplicates\n",
    "    _, peptide_ids = np.unique(df['Peptide'], return_inverse=True)    \n",
    "    df_tcr = df.rename(columns={\n",
    "        'CDR3a': 'cdr3_a_aa',\n",
    "        'CDR3b': 'cdr3_b_aa',\n",
    "        'Va': 'v_a_gene',\n",
    "        'Vb': 'v_b_gene',\n",
    "    })"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5c3b6ae1-1575-43ad-bc5e-8a4c7f63be68",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cdr3_a_aa</th>\n",
       "      <th>cdr3_b_aa</th>\n",
       "      <th>v_a_gene</th>\n",
       "      <th>v_b_gene</th>\n",
       "      <th>peptide</th>\n",
       "      <th>peptide_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>CIVRAPGRADMRF</td>\n",
       "      <td>CASSYLPGQGDHYSNQPQHF</td>\n",
       "      <td>TRAV26-1*01</td>\n",
       "      <td>TRBV13*01</td>\n",
       "      <td>FLKEKGGL</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>CAVPSGAGSYQLTF</td>\n",
       "      <td>CASSFEPGQGFYSNQPQHF</td>\n",
       "      <td>TRAV20*01</td>\n",
       "      <td>TRBV13*01</td>\n",
       "      <td>FLKEKGGL</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>CAVKASGSRLT</td>\n",
       "      <td>CASSYEPGQVSHYSNQPQHF</td>\n",
       "      <td>TRAV2*01</td>\n",
       "      <td>TRBV13*01</td>\n",
       "      <td>FLKEKGGL</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>CAYRPPGTYKYIF</td>\n",
       "      <td>CASSALASLNEQFF</td>\n",
       "      <td>TRAV38-2/DV8*01</td>\n",
       "      <td>TRBV14*01</td>\n",
       "      <td>FLKEKGGL</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>CIVRAPGRADMRF</td>\n",
       "      <td>CASSYLPGQGDHYSNQPQHF</td>\n",
       "      <td>TRAV26-1*01</td>\n",
       "      <td>TRBV13*01</td>\n",
       "      <td>FLKEQGGL</td>\n",
       "      <td>70</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2820</th>\n",
       "      <td>CIALNARLMF</td>\n",
       "      <td>CASSLRATDTQYF</td>\n",
       "      <td>TRAV26-1*01</td>\n",
       "      <td>TRBV7-2*01</td>\n",
       "      <td>PQPELPYPQPQL</td>\n",
       "      <td>233</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2821</th>\n",
       "      <td>CAMREGRYSSASKIIF</td>\n",
       "      <td>CATSRAGGGGEKLFF</td>\n",
       "      <td>TRAV14/DV4*01</td>\n",
       "      <td>TRBV15*01</td>\n",
       "      <td>FPQPEQPFPWQP</td>\n",
       "      <td>79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2822</th>\n",
       "      <td>CLVGDGDGGATNKLIF</td>\n",
       "      <td>CASSQGSGGNEQFF</td>\n",
       "      <td>TRAV4*01</td>\n",
       "      <td>TRBV4-3*01</td>\n",
       "      <td>FPQPEQPFPWQP</td>\n",
       "      <td>79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2823</th>\n",
       "      <td>CAASVLYGSSNTGKLIF</td>\n",
       "      <td>CASSIVGSGGYNEQFF</td>\n",
       "      <td>TRAV29/DV5*01</td>\n",
       "      <td>TRBV19*01</td>\n",
       "      <td>QLQPFPQPELPY</td>\n",
       "      <td>242</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2824</th>\n",
       "      <td>CAPQGATNKLIF</td>\n",
       "      <td>CASSLGAGGQETQYF</td>\n",
       "      <td>TRAV12-2*01</td>\n",
       "      <td>TRBV5-1*01</td>\n",
       "      <td>PQQPFPQPEQPFP</td>\n",
       "      <td>234</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2335 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "              cdr3_a_aa             cdr3_b_aa         v_a_gene    v_b_gene  \\\n",
       "0         CIVRAPGRADMRF  CASSYLPGQGDHYSNQPQHF      TRAV26-1*01   TRBV13*01   \n",
       "1        CAVPSGAGSYQLTF   CASSFEPGQGFYSNQPQHF        TRAV20*01   TRBV13*01   \n",
       "2           CAVKASGSRLT  CASSYEPGQVSHYSNQPQHF         TRAV2*01   TRBV13*01   \n",
       "3         CAYRPPGTYKYIF        CASSALASLNEQFF  TRAV38-2/DV8*01   TRBV14*01   \n",
       "4         CIVRAPGRADMRF  CASSYLPGQGDHYSNQPQHF      TRAV26-1*01   TRBV13*01   \n",
       "...                 ...                   ...              ...         ...   \n",
       "2820         CIALNARLMF         CASSLRATDTQYF      TRAV26-1*01  TRBV7-2*01   \n",
       "2821   CAMREGRYSSASKIIF       CATSRAGGGGEKLFF    TRAV14/DV4*01   TRBV15*01   \n",
       "2822   CLVGDGDGGATNKLIF        CASSQGSGGNEQFF         TRAV4*01  TRBV4-3*01   \n",
       "2823  CAASVLYGSSNTGKLIF      CASSIVGSGGYNEQFF    TRAV29/DV5*01   TRBV19*01   \n",
       "2824       CAPQGATNKLIF       CASSLGAGGQETQYF      TRAV12-2*01  TRBV5-1*01   \n",
       "\n",
       "            peptide  peptide_id  \n",
       "0          FLKEKGGL          68  \n",
       "1          FLKEKGGL          68  \n",
       "2          FLKEKGGL          68  \n",
       "3          FLKEKGGL          68  \n",
       "4          FLKEQGGL          70  \n",
       "...             ...         ...  \n",
       "2820   PQPELPYPQPQL         233  \n",
       "2821   FPQPEQPFPWQP          79  \n",
       "2822   FPQPEQPFPWQP          79  \n",
       "2823   QLQPFPQPELPY         242  \n",
       "2824  PQQPFPQPEQPFP         234  \n",
       "\n",
       "[2335 rows x 6 columns]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_tcr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "930a63e6-babf-4525-bea5-246fa3068dba",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:159: UserWarning: cell_df needs a counts column to track clonal number of frequency\n",
      "\n",
      "  self._validate_cell_df()\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:791: UserWarning: No 'count' column provided; count column set to 1\n",
      "  warnings.warn(\"No 'count' column provided; count column set to 1\")\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14D-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV9-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6D-7*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV21/DV12*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6N-7*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV9D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV5N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14D-3/DV8*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV3-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7D-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV10N*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14N-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14D-3/DV8*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV14D-3/DV8*08 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV3N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV3-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV12D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV8D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV13N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV16D/DV11*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV9N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6D-6*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-4*03 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6N-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV12N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6D-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6N-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV9N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV8N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV16D/DV11*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV12N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-5*04 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-7/DV9*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV15N-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV15-1/DV6-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV16N*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV8D-2*03 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7D-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7-3*04 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7N-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV9-1*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV3-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV3D-3*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV7N-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV5-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV9N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV11*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV6-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV13-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRAV4-4/DV10*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14D-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV9-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6D-7*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV21/DV12*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6N-7*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV9D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV5N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14D-3/DV8*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV3-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7D-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV10N*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14N-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14D-3/DV8*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV14D-3/DV8*08 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV3N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV3-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV12D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV8D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV13N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV16D/DV11*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV9N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6D-6*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-4*03 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6N-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV12N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6D-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6N-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV9N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV8N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV16D/DV11*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV12N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-5*04 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-7/DV9*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV15N-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV15-1/DV6-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV16N*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV8D-2*03 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7D-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7-3*04 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7N-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV9-1*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV3-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV3D-3*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV7N-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV5-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV9N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV11*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV6-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV13-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRAV4-4/DV10*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14D-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV9-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6D-7*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV21/DV12*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6N-7*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV9D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV5N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14D-3/DV8*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV3-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7D-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV10N*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14N-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14D-3/DV8*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV14D-3/DV8*08 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV3N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV3-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV12D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV8D-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV13N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV16D/DV11*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV9N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6D-6*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-4*03 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6D-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6N-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV12N-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6D-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6N-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV9N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV8N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV16D/DV11*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV12N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-5*04 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-7/DV9*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV15N-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV15-1/DV6-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV16N*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV8D-2*03 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7D-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7D-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7-3*04 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7N-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7N-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV9-1*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV3-4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV3D-3*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV7N-6*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4-2*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV5-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV9N-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV11*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV6-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV13-5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRAV4-4/DV10*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV13-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV13-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV29*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV13-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV31*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV13-1*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV20*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV23*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:500: UserWarning: TRBV24*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f0 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV13-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV13-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV29*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV13-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV31*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV13-1*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV20*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV23*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:504: UserWarning: TRBV24*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f1 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV13-2*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV13-3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV29*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV13-1*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV4*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV5*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV31*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV13-1*02 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV3*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV20*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV23*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:508: UserWarning: TRBV24*01 gene was not recognized in reference db no cdr seq could be inferred\n",
      "  f2 = lambda v : self._map_gene_to_reference_seq2(gene = v,\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:833: FutureWarning: The provided callable <function sum at 0x105d436d0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string \"sum\" instead.\n",
      "  clones = cell_df.groupby(index_cols)['count'].agg(np.sum).reset_index()\n",
      "/Users/axelr/pll/venv/lib/python3.10/site-packages/tcrdist/repertoire.py:190: UserWarning: Not all cells/sequences could be grouped into clones.752 of 2335 were not captured. This occurs when any of the values in the index columns are null or missing for a given sequence. To see entries with missing values use: tcrdist.repertoire.TCRrep._show_incomplete()\n",
      "  self.deduplicate()\n"
     ]
    }
   ],
   "source": [
    "from tcrdist.repertoire import TCRrep\n",
    "# tcrdist complains a lot, and drops quite a lot of data. I just ignored that\n",
    "\n",
    "rep = TCRrep(organism='human', cell_df=df_tcr)\n",
    "rep.compute_distances()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "ed69b8d5-0803-4070-8430-17442a97a645",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1583, 14)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "rep.clone_df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "cea1a3ba-1725-44cb-a124-8247df84de92",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "((1583, 1583), (2335, 7))"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# see how much data was discarded\n",
    "distances = rep.pw_cdr3_b_aa\n",
    "distances.shape, df_tcr.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "e6f2c04c-797e-4ebe-b960-73f2c8b9c705",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.2543693409138766\n",
      "0.2695304274584123\n",
      "0.3051168667087808\n"
     ]
    }
   ],
   "source": [
    "for dist in [\n",
    "    rep.pw_cdr3_a_aa,\n",
    "    rep.pw_cdr3_b_aa,\n",
    "    rep.pw_cdr3_a_aa + rep.pw_cdr3_b_aa,\n",
    "]:\n",
    "    peptide_ids = rep.clone_df['peptide_id'].values\n",
    "    arg = argsort(dist  + np.eye(len(dist)) * 10_000, 'i j -> [i] j order')[:, :, :3].copy()\n",
    "    mask = gather_scatter(peptide_ids, arg, 'i, [i] j order -> j order') == peptide_ids[:, None]\n",
    "    score = mask.mean(axis=1)\n",
    "    print(score.mean())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
